import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LoadingSpinner from './components/LoadingSpinner';
import '../app/globals.css';
import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import('./page'), {
    loading: () => <LoadingSpinner />,
    ssr: false,
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Portfolio Website',
    description: 'Generated by create next app',
    icons: '/images/briefcase-logo.png',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <DynamicHeader />
            </body>
        </html>
    )
}
